name: Build and deploy to Azure

on:
  push:
    branches:
    - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions'
  NODE_VERSION: '14.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: 'Resolve Project Dependencies Using Npm'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd
    - name: 'Deploy Azure Functions to Europe'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.AZUREAPPSERVICE_APPNAME }}
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EU }}
    - name: 'Deploy Azure Functions to the US'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.AZUREAPPSERVICE_APPNAME }}
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFIL_US }}
    - name: 'Deploy Azure Functions to Asia'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.AZUREAPPSERVICE_APPNAME }}
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ASIA }}
